model:
  name: potential_model
  params:
    e_dress:
      1: -0.15942758189641976
      6: 0.2841832528303877
      7: 0.34114343845590056
      8: 0.16951928437807914
      9: -0.014469471104331198
      15: 0.6140282465537565
      16: 0.435885135606164
      17: 0.2348091635852471
    e_loss_multiplier: 1.0
    e_scale: 1.0
    e_unit: 1.0
    f_loss_multiplier: 10.0
    log_e_per_atom: true
    use_e_per_atom: false
    use_force: false
model_dir: PiNet2-EA-B10-3E6-8
network:
  name: PiNet2
  params:
    atom_types:
    - 1
    - 6
    - 7
    - 8
    - 9
    - 15
    - 16
    - 17
    basis_type: gaussian
    depth: 5
    ii_nodes:
    - 64
    - 64
    - 64
    - 64
    n_basis: 15
    out_nodes:
    - 64
    pi_nodes:
    - 64
    pp_nodes:
    - 64
    - 64
    - 64
    - 64
    rank: 3
    rc: 4.5
    weighted: false
optimizer:
  class_name: Adam
  config:
    global_clipnorm: 0.01
    learning_rate:
      class_name: ExponentialDecay
      config:
        decay_rate: 0.98
        decay_steps: 100000
        initial_learning_rate: 0.0001
